### ISSUE TITLE
DMDWebGen erzeugt keine *Panel.html

### ISSUE THREAD

**Issue by meisterDusi** [Nocket/nocket#6]
DMDWebGen erzeugt immer eine Page.html-Datei,  keine *Panel.html. Auch nicht, wenn eine existierende *Panel.java-Datei vorhanden ist. 
Das Problem liegt in GroupNameFileAndClassNameStrategy.isPanel(). Dort sollte auf die Existenz der *Panel.java-Datei geachtet werden.

**Comment by ablazek** [comment]
Du brauchst hier nichts mehr tun. Alle bekannte Probleme mit der Generierung habe ich in "templates" branch gefixt.

**Comment by jereh16** [comment]
templates branch wurde in master gemerged und als R0.4.1 veröffentlicht
